name: Rust CI/CD

on:
    push:
        tags: ["v.[0-9]+.[0-9]+.[0-9]+"]

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release
            - uses: actions/upload-artifact@v3
              with:
                  name: a.out
                  path: target/release/github_actions_test

    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: test

    fmt:
        name: formatter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - run: rustup component add rustfmt
            - uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check

    clippy:
        name: linter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - run: rustup component add clippy
            - uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: -- -D warnings

    release:
        name: release
        needs: [build, test, fmt, clippy]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: a.out
            - uses: softprops/action-gh-release@v1
              with:
                  files: a.out
