name: variable_and_secret

on:
    push:
        branches: [master]

jobs:
    variables:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ vars.repo_var }}"

            #gives the same result as above but is slightly different how the log looks
            - run: echo "${REPO_VAR}"
              env:
                  REPO_VAR: ${{ vars.repo_var }}

    secrets:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${REPO_SEC}"
              env:
                  REPO_SEC: ${{ secrets.repo_sec }}

    ssh:
        runs-on: ubuntu-latest
        env:
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
        steps:
            - run: echo "${SSH_KEY}" > id_rsa
            - run: ssh -i id_rsa "${SSH_USER}@${SSH_HOST}" uptime
