name: variable_and_secret

on:
    push:
        branches: [master]

jobs:
    variables:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${REPO_VAR}"
              env:
                  REPO_VAR: ${{ vars.repo_var }}
