name: variable_and_secret

on:
    push:
        branches: [master]

jobs:
    variables:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${REPO_VAR}"
              env:
                  REPO_VAR: ${{ vars.repo_var }}

    secrets:
        runs-on: ubuntu-latest
        steps:
            #This is unsafe as the expansion result is printed in an log entry.
            - run: echo "${{ secrets.repo_sec }}"

            #This is safer.
            - run: echo "${REPO_SEC}"
              env:
                  REPO_SEC: ${{ secrets.repo_sec }}
